### ISSUE TITLE
PaulsXstretch functionality? feature request

### ISSUE THREAD

**Issue by jgrimsong** [stretta/TextureExplorer#8]
What you have here has some similarities to the dormant PaulsXstretch. Is there any chance you can add some of that feature set? Or is that another piece of software entirely? I love that plugin but it has been abandoned and I have yet to see a modern MFL re-design or anything similar. Now I'm having crash problems with it in Abelton 10 and it probably should not be possible to run anymore anyhow. Anyway, just thought I would throw that idea out there. TextureExplorer is great BTW!!

**Comment by stretta** [comment]
I have heard of Paul Stretch, but I have never used it. I assumed the underlying technology was a phase vocoder. I added a phase vocoder M4L device to the [Stretta Inspiration Suite](https://github.com/stretta/Stretta-Inspiration-Tools) for you by adapting the Phase Vocoder from Beap with an LFO to drive the position for stretching/freezing effects. Maybe this will work for you.
